[project]
name = "user-report-generator-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["requests (>=2.32.3,<3.0.0)"]
[tool.poetry]
name = "user-report-generator-python"
version = "0.1.0"
package-mode = false
